name: 02- workflow events
on:
    push

jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "runs of event ${{github.event_name}}"


