name: 02- workflow events
on:
    push:
    pull_request:
    schedule:
        - cron: '*/2****'
    workflow_dispatch:

jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "runs event - ${{github.event_name}}"


